### ISSUE TITLE
Doesn't support media queries

### ISSUE THREAD

**Issue by stevenvachon** [code-and-send/email-remove-unused-css#3]
```js
[Error: TypeError: Cannot read property 'length' of undefined
```
from
```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<title>test</title>
<style>
@media screen {
  .class {
    color: black;
  }
}
</style>
</head>
<body></body>
</html>
```

**Comment by revelt** [comment]
Updated! Media queries were recognised fine, it was the particular case of empty styles being fed into CSS stringify and it `throw`ing as a result. I tightened the catch-net to filter out what gets stringified and all seem to work fine now.

Thanks Steven!

**Comment by stevenvachon** [comment]
Awesome. Thanks!
